name: Run Screen Mirror on Workflow Dispatch

on:
  workflow_dispatch:  # This allows manual trigger from the GitHub UI

jobs:
  run-screen-mirror:
    runs-on: macos-latest  # You can also use other runners like 'windows-latest' if needed
    steps:
    
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up Python environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyautogui supabase pillow
    
    # Step 4: Set up environment variables from GitHub Secrets
    - name: Set up environment variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
    
    # Step 5: Run the screen-mirroring script
    - name: Run screen-mirroring script
      run: |
        python screen_mirror.py  # Make sure your Python script is named "screen_mirror.py" or adjust accordingly
